Use of enumerate rather than explicit counter def.

diff --git a/wis2downloader/Dockerfile b/wis2downloader/Dockerfile
--- a/wis2downloader/Dockerfile
+++ b/wis2downloader/Dockerfile
@@ -1,46 +1,67 @@
-# Use an official Python runtime as a parent image
-FROM python:3.9-slim
+FROM python:3.12-slim-bookworm
 
-EXPOSE 5000
+SHELL ["/bin/bash", "-c"]
 
-# define config variables
-ENV DOWNLOAD_DIR /app/downloads
-ENV DOWNLOAD_RETENTION_PERIOD_HOURS 24
+# default ENV / config
 ENV DOWNLOAD_BROKER_HOST "globalbroker.meteo.fr"
 ENV DOWNLOAD_BROKER_PORT 443
 ENV DOWNLOAD_BROKER_USERNAME "everyone"
 ENV DOWNLOAD_BROKER_PASSWORD "everyone"
 ENV DOWNLOAD_BROKER_TRANSPORT "websockets"
-ENV DOWNLOAD_WORKERS 8
+ENV DOWNLOAD_DIR "/app/downloads"
 ENV DOWNLOAD_MIN_FREE_SPACE_GB 1
+ENV DOWNLOAD_RETENTION_PERIOD_HOURS 24
 ENV DOWNLOAD_VALIDATE_TOPICS "false"
-ENV LOG_PATH /app/logs
-ENV WIS2DOWNLOADER_CONFIG "/app/config.json"
+ENV DOWNLOAD_WORKERS 8
+ENV LOG_PATH "/home/wis2downloader/app/logs"
+ENV WIS2DOWNLOADER_CONFIG "/home/wis2downloader/app/config/config.json"
+ENV USER_ID 12135
 
-# update pyopenssl and pin requests and urllib3 to avoid SSL error
-RUN pip install pyopenssl --upgrade && pip install requests==2.26.0 urllib3==1.26.0
-# install cron and envsubst and guincorn
-RUN apt-get update && apt-get install -y cron gettext-base gunicorn
+# Update, upgrade packages and install / clean up
+RUN apt-get update && \
+    apt-get upgrade && \
+    apt-get install -y gettext-base=0.21-12 curl=7.88.1-10+deb12u6 cron=3.0pl1-162 git=1:2.39.2-1.1 && \
+    rm -rf /var/lib/apt/lists/*
 
-# copy all the code to the Docker image
-COPY . /app
+# Now setup python env and default user
+RUN useradd -l -u "$USER_ID" wis2downloader
 
+USER wis2downloader
+WORKDIR /home/wis2downloader
+
+USER wis2downloader
+
+RUN python3.12 -m venv /home/wis2downloader/.venv && \
+    echo "source /home/wis2downloader/.venv/bin/activate" >> .bashrc && \
+    echo "" >> .bashrc
+
+# install python dependencies
+RUN source /home/wis2downloader/.venv/bin/activate && \
+    python -m pip install --no-cache-dir gunicorn==23.0.0 requests==2.32.3 && \
+    python -m pip install --no-cache-dir pyopenssl==24.2.1 --upgrade && \
+    python -m pip install --no-cache-dir wis2downloader==0.3.0 # git+https://github.com/wmo-im/wis2downloader@docker2
+
+# copy config and entrypoint to the Docker image
+COPY config/. /home/wis2downloader/app/config
+COPY entrypoint.sh /home/wis2downloader/app/entrypoint.sh
+COPY clean_downloads.cron /home/wis2downloader/app/clean_downloads.cron
+COPY clean_downloads.py /home/wis2downloader/app/clean_downloads.py
+
+USER root
+RUN chown -R wis2downloader /home/wis2downloader/app && \
+    chmod +x /home/wis2downloader/app/entrypoint.sh && \
+    chmod 600 /home/wis2downloader/app/clean_downloads.py && \
+    chmod 600 /home/wis2downloader/app/clean_downloads.cron
+
+USER wis2downloader
 # Set the working directory to /app
-WORKDIR /app
+WORKDIR /home/wis2downloader
+RUN crontab ./app/clean_downloads.cron
 
-# install wis2downloader from pypi
-RUN pip install wis2downloader
+# Add healthcheck
+HEALTHCHECK --interval=1m --timeout=3s \
+  CMD curl -f http://localhost:5000/subscriptions || exit 1
 
-# add wis2box.cron to crontab
-COPY ./clean.cron /etc/cron.d/clean.cron
-
-# set permissions for the cron job and install it
-RUN chmod 0644 /etc/cron.d/clean.cron && crontab /etc/cron.d/clean.cron
-
-# set permissions for the entrypoint script
-RUN chmod +x /app/entrypoint.sh
-
-ENTRYPOINT [ "/app/entrypoint.sh" ]
-
+ENTRYPOINT [ "/home/wis2downloader/app/entrypoint.sh" ]
 # Run wis2downloader when the container launches
-CMD ["gunicorn","--bind","0.0.0.0:5000","--pythonpath","/usr/local/lib/python3.9/site-packages/","--workers", "1", "wis2downloader.app:app"]
+CMD ["/bin/bash", "-c", "gunicorn --bind 0.0.0.0:5000 --workers 1 wis2downloader.app:app"]
